"use client";

import * as React from "react";

/**
 * Figma draws the collapsible at two sizes (`924:1837`), and the two differ in more
 * than a padding: the shell gains a border and a bigger radius, the label moves from
 * `Label/Medium/Medium` to `Body/Large/SemiBold`, the icons from 16px to 24px, the
 * panel from a tinted inner box to bare padding — and, most of all, *what is
 * clickable* changes. At `default` the whole row is the button; at `large` only a
 * 40×40 button at its end is.
 *
 * Six correlated differences is one decision, so it is one prop on the root rather
 * than one on every part. And the parts are composed by the consumer — they are
 * siblings in the caller's JSX, not children this component hands props to — so the
 * root publishes the decision and each part reads it.
 */
type CollapsibleSize = "default" | "large";

type CollapsibleContextValue = {
  size: CollapsibleSize;
  /**
   * Radix writes `data-disabled` onto the parts it owns — the root, the trigger, the
   * content — but `CollapsibleHeader` is ours, so nothing marks it. It reads the flag
   * from here instead of the consumer having to disable the row twice.
   */
  disabled: boolean;
  /**
   * The id the root minted for `CollapsibleLabel`, so that `CollapsibleToggle` can name
   * itself from the label instead of from a string the consumer has to remember to
   * pass. Generated by the root because both parts need to agree on it and neither can
   * see the other.
   */
  labelId: string | undefined;
  /**
   * Whether a `Collapsible` is actually above this part, as opposed to the part being
   * rendered on its own. Only the composition check below reads it: a lone
   * `CollapsibleHeader` in a story has no size to disagree with, so it must not warn.
   */
  hasRoot: boolean;
};

const CollapsibleContext = React.createContext<CollapsibleContextValue>({
  size: "default",
  disabled: false,
  labelId: undefined,
  hasRoot: false,
});

/**
 * Publishes the size, disabled state and label id to the parts. Rendered by
 * `Collapsible`.
 */
const CollapsibleProvider = CollapsibleContext.Provider;

/**
 * The size, disabled state and label id of the nearest enclosing `Collapsible`.
 *
 * Falls back to `{ size: "default", disabled: false }` rather than throwing, so a part
 * rendered on its own — in a test, in a story that shows one row — still draws
 * something. A collapsible with no root is a composition error the type system does
 * not catch, but it is not worth a runtime crash in a design system: the fallback is
 * the size the design calls default.
 *
 * @returns {{ size: 'default' | 'large', disabled: boolean, labelId?: string, hasRoot: boolean }}
 */
function useCollapsible() {
  return React.useContext(CollapsibleContext);
}

/**
 * Warns, in development only, when a part is used at the size it is not for.
 *
 * The two sizes are two *compositions*, not one composition with different padding:
 * `default` is `CollapsibleTrigger`, `large` is `CollapsibleHeader` + `CollapsibleToggle`.
 * Mixing them type-checks, renders and looks nearly right — a `CollapsibleTrigger` at
 * `size="large"` draws 16px icons and the compact radius inside a bordered card — so
 * nothing tells you except a careful look at the result.
 *
 * A warning rather than making the wrong pairing work, because making it work would
 * contradict the design: at `large` the row is deliberately not a click target, so a
 * `CollapsibleTrigger` that quietly restyled itself would still be a `<button>` around
 * whatever badge or menu the row holds.
 *
 * Stripped from a production build by the `NODE_ENV` check. Written as a bare
 * `process.env.NODE_ENV`, which every bundler replaces with a string literal so the
 * branch folds away — not guarded with `typeof process !== "undefined"`, which reads as
 * the safer spelling and is the opposite: bundlers substitute the member expression but
 * leave `typeof process` alone, so in a browser the guard is false and the warning
 * never fires anywhere. This is the form React itself ships.
 *
 * @param {'default' | 'large'} expected - The size this part belongs to
 * @param {string} part - The part's name, for the message
 * @returns {'default' | 'large'} The size in context
 */
function useSizedFor(expected: CollapsibleSize, part: string): CollapsibleSize {
  const { hasRoot, size } = useCollapsible();

  React.useEffect(() => {
    if (process.env.NODE_ENV === "production") return;
    if (!hasRoot || size === expected) return;

    const advice =
      expected === "default"
        ? 'At size="large" the row is inert: use CollapsibleHeader with a CollapsibleToggle in it.'
        : 'At size="default" the whole row is the button: use CollapsibleTrigger.';

    console.warn(
      `[Collapsible] ${part} is for size="${expected}", but this one is inside a Collapsible with size="${size}". ${advice}`,
    );
  }, [expected, hasRoot, part, size]);

  return size;
}

export { CollapsibleProvider, useCollapsible, useSizedFor, type CollapsibleSize };
